# Generated by Django 5.2.5 on 2025-08-20 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LAFapp", "0002_items_created_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="categoly",
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="items",
            name="key_word",
            field=models.CharField(blank=True, null=True),
        ),
    ]
