# Generated by Django 5.2.5 on 2025-08-20 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LAFapp", "0003_items_categoly_items_key_word"),
    ]

    operations = [
        migrations.RenameField(
            model_name="items",
            old_name="categoly",
            new_name="category",
        ),
    ]
