# Generated by Django 5.2.5 on 2025-08-22 13:39

import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LAFapp", "0004_rename_categoly_items_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
    ]
