# Generated by Django 5.2.5 on 2025-08-24 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("LAFapp", "0005_items_search_vector"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="items",
            name="search_vector",
        ),
    ]
