# Generated by Django 5.2.5 on 2025-09-05 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LAFapp", "0006_remove_items_search_vector"),
    ]

    operations = [
        migrations.AddField(
            model_name="items",
            name="completed",
            field=models.BooleanField(default=False),
        ),
    ]
